"""create initial matches table

Revision ID: a4f0eea16b34
Revises: 
Create Date: 2026-06-18 03:23:44.658171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f0eea16b34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('radiant_team_id', sa.BigInteger(), nullable=True),
    sa.Column('radiant_name', sa.String(), nullable=True),
    sa.Column('dire_team_id', sa.BigInteger(), nullable=True),
    sa.Column('dire_name', sa.String(), nullable=True),
    sa.Column('leagueid', sa.BigInteger(), nullable=False),
    sa.Column('league_name', sa.String(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('series_type', sa.Integer(), nullable=True),
    sa.Column('radiant_score', sa.Integer(), nullable=False),
    sa.Column('dire_score', sa.Integer(), nullable=False),
    sa.Column('radiant_win', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('flag_details_collected', sa.Boolean(), nullable=False),
    sa.Column('flag_details_processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
